# Generated by Django 6.0 on 2025-12-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                ("room_id", models.CharField(max_length=20, verbose_name="房间号")),
                (
                    "customer_name",
                    models.CharField(max_length=50, verbose_name="客户姓名"),
                ),
                ("card_id", models.CharField(max_length=50, verbose_name="RFID卡号")),
                (
                    "action_type",
                    models.CharField(
                        default="CHECK_IN", max_length=20, verbose_name="操作类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "客房入住记录",
                "verbose_name_plural": "客房入住记录",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=100, verbose_name="备份文件名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="备份时间"),
                ),
            ],
        ),
    ]
