# Generated by Django 6.0 on 2025-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systembackup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "系统数据备份",
                "verbose_name_plural": "系统数据备份",
            },
        ),
        migrations.RenameField(
            model_name="checkinrecord",
            old_name="card_id",
            new_name="rfid_tag",
        ),
        migrations.RemoveField(
            model_name="checkinrecord",
            name="action_type",
        ),
        migrations.AddField(
            model_name="checkinrecord",
            name="id_card_num",
            field=models.CharField(blank=True, max_length=30, verbose_name="身份证号"),
        ),
        migrations.AddField(
            model_name="systembackup",
            name="file_path",
            field=models.CharField(default="", max_length=255, verbose_name="文件路径"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systembackup",
            name="size_kb",
            field=models.FloatField(default=0, verbose_name="大小(KB)"),
        ),
        migrations.AlterField(
            model_name="checkinrecord",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="入住时间"),
        ),
    ]
