# Generated by Django 6.0 on 2025-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_hotel", "0002_alter_systembackup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RfidLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=50, verbose_name="卡号")),
                ("room_number", models.CharField(max_length=20, verbose_name="房间号")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="刷卡时间"),
                ),
                ("raw_event", models.CharField(default="card_swipe", max_length=50)),
            ],
            options={
                "verbose_name": "刷卡日志",
                "verbose_name_plural": "刷卡日志",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RoomStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(max_length=20, unique=True, verbose_name="房间号"),
                ),
                ("status", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="住客姓名"
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=100, verbose_name="设备ID"),
                ),
            ],
            options={
                "verbose_name": "房间实时状态",
                "verbose_name_plural": "房间实时状态",
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                ("message", models.TextField(verbose_name="日志内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="CheckInRecord",
        ),
        migrations.AlterModelOptions(
            name="systembackup",
            options={"ordering": ["-created_at"]},
        ),
    ]
